### ISSUE TITLE
WSL2の移行方法について

### ISSUE THREAD

**Issue by ilukame** [yappy/WslMemo#1]
「仮想マシン機能の有効化」のあと**再起動**しないと「WSL デフォルトバージョンの変更」がうまくいかなかった。
PowerShell にも再起動しろなんて出なかったから一言書いておいてほしい。公式には書いてあるけど。

**Comment by yappy** [comment]
BIOS の設定いじってる時に自然に再起動挟まって気づかなかったか、ただ単純に書き忘れたのか分かりませんが
とりあえず書いておきますか
どちらかというと公式へのリンク追加の方が重要な気がするけど
